
server.servlet.context-path: /api

spring :
  datasource:
    url: jdbc:mysql://localhost:3306/java_shop?setUnicode=true&characterEncoding=utf8
    username: root
    password: 123456


mybatis:
  configuration:
    map-underscore-to-camel-case: true
